alias ls='php artisan serve'
alias lsp='php artisan serve --port=$port'
alias lt='php artisan migrate'
alias ltb='php artisan migrate:rollback'
alias ltr='php artisan migrate:refresh'
alias lo='php artisan optimize:clear'
alias cls='clear'
alias lc='php artisan make:controller $name'
alias lm='php artisan make:model $name'
alias lmm='php artisan make:model $name -m'
alias lmmc='php artisan make:model $name -mc'
alias lmmrc='php artisan make:model $name -mcr'
alias lurl='php artisan route:list'
alias lp='laravel new $name'
alias npmdev='npmdev'
